spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_demo"
    username: "postgres"
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG
    org.springframework: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}

transaction:
  max-count: 3

client:
  service:
    url: http://localhost:8081
